<div class="class-accordion">
<?php foreach ($block->getFAQ() as $item): ?>

    <!-- show only enable question-answer -->
    <?php if ($item->getStatus() == 1){
    ?>
<button class="accordion"><?php echo $item->getQuestion(); ?></button>
    <div class="panel">
        <?php echo $item->getAnswer(); ?>
    </div>
    <div class="my-line-accordion"></div>
    <?php
    }
    ?>

<?php endforeach; ?>
</div>

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight){
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
            }
        });
    }
</script>
